### ISSUE TITLE
Sources.list.d duplicate entries for OpenCPN

### ISSUE THREAD

**Issue by andyrbarrow** [openplotter/openplotter-settings#1]
It's not a huge issue right now, but I just tried installing openplotter-settings on my Linux laptop. I already had OpenCPN installed. 
The script put in the openplotter.list file, which had a duplicate entry for OpenCPN, which causes apt to create an error.
It would probably be best for the script to check for a previous sources.list.d entry for OpenCPN (and perhaps other programs) before it inserts openplotter.list.
Again, not a huge issue, and I know that generic Linux isn't a priority right now. Just something to remember as things develop.

**Comment by sailoog** [comment]
you are the second one reporting this, I guess we can do something. Thanks.

**Comment by sailoog** [comment]
Fixed
