### ISSUE TITLE
Dependency on python-configparser

### ISSUE THREAD

**Issue by MennoTammens** [openplotter/openplotter-settings#10]
openplotter-settings depends on the Debian/Ubuntu package _python-configparser_:

> **python-configparser**
> backport of the enhanced config parser introduced in Python 3.2
> 
> The ancient ConfigParser module available in the standard library 2.x has seen a major update in Python 3.2. This is a backport of those changes so that they can be used directly in Python 2.7. 

This package is for Python 2.x, and can be removed as dependency because it is part of the standard library in Python 3.2+

**Comment by sailoog** [comment]
Thanks!
