### ISSUE TITLE
Add support for lysmarine BBN OS

### ISSUE THREAD

**Issue by mgrouch** [openplotter/openplotter-settings#14]
Add support for lysmarine BBN OS. 
It's based on raspi OS. To detect BBN OS you could check the presence
of the file 

/etc/bbn-build

Linked issue: https://github.com/bareboat-necessities/lysmarine_gen/issues/18

Thanks

**Comment by sailoog** [comment]
Any system based on Raspberry OS should be supported out of the box. Reopen if you found any issue installing openplotter in your system: https://openplotter.readthedocs.io/en/latest/getting_started/installing.html#advanced

**Comment by mgrouch** [comment]
Installing is not the issue. It installs fine. 
It doesn't work properly after install. 

I can't seem to re-open though.

Thanks

**Comment by sailoog** [comment]
then open issues in the specific app repository where you find problems.
