### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [openplotter/openplotter-settings#15]
Hi, can you add the following topics to this repository?
* https://github.com/topics/openplotter
* https://github.com/topics/boat
* https://github.com/topics/boating
* https://github.com/topics/marine
* https://github.com/topics/sailing
* https://github.com/topics/sdr
* https://github.com/topics/ais

Thanks!

**Comment by sailoog** [comment]
Sure

**Comment by mendel5** [comment]
Thank you!
