### ISSUE TITLE
isAlive() AttributeError

### ISSUE THREAD

**Issue by masc-git** [openplotter/openplotter-settings#16]
on a recent debian unstable (openplotter-settings 2.8.1-stable, python 3.9.7) i get with the manual installation errors when starting 'openplotter-startup check':

  File "/usr/lib/python3/dist-packages/openplotterSettings/startup.py", line 71, in __init__
    if not self.thread1.isAlive(): self.thread1.start()
  AttributeError: 'Thread' object has no attribute 'isAlive'
  File "/usr/lib/python3/dist-packages/openplotterSettings/startup.py", line 114, in refresh
    if not self.thread1.isAlive(): self.OnCloseButton()
  AttributeError: 'Thread' object has no attribute 'isAlive'

internet search says it might be the is_alive() attribute, changing the two lines fixes this problem.

**Comment by sailoog** [comment]
It seems that isAlive has been deprecated in favour of is_alive()
could you please check your python version with "python -V"?

**Comment by masc-git** [comment]
3.9.7

**Comment by sailoog** [comment]
OK, thanks. I will test if is_alive() is digested by the current python version in stable Debian buster and I will change it.

**Comment by sailoog** [comment]
closed by https://github.com/openplotter/openplotter-settings/commit/d4d763949098eca5090b9e1ba50394f008acff04
thanks!
