### ISSUE TITLE
XyGrib for Debian bullseye

### ISSUE THREAD

**Issue by sailoog** [openplotter/openplotter-settings#17]
Hi @free-x , do you have plans to add XyGrib for bullseye in your repository?

**Comment by free-x** [comment]
hi @sailoog,

as i know, XyGrib is a part of Bullseye 
https://packages.debian.org/bullseye/xygrib
does something not fit?

greetings
free-x

**Comment by sailoog** [comment]
ops, I did not know that, I will try that in OpenPlotter 3. Thanks!

**Comment by free-x** [comment]
but unfortunately there are no newer releases.
I would like to continue to provide OP with AvNav packages from my repository in the future. But we are not yet ready to release repository for bullseye.

**Comment by sailoog** [comment]
You are right, I forgot the AvNav app was in your repository too. Do not worry we have just started with OpenPlotter 3 and bullseye and it will take some months of work. I will let you know when we are close to a stable version. Thanks.

**Comment by free-x** [comment]
we are very well on schedule. we are only missing avnav-ocharts-provider for arm64. First image for "armhf" I had already finished in september ;-) and already tested extensively.
Let me hear, if you are missing something and need it urgently I will package it with pleasure.

**Comment by sailoog** [comment]
I am getting this error on ubuntu 20.04:
```

Err:7 https://www.free-x.de/deb4op bullseye Release
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 195.201.226.168 443]
Reading package lists...
E: The repository 'https://www.free-x.de/deb4op bullseye Release' does not have a Release file.
```
It is working right in Raspberry OS

**Comment by free-x** [comment]
@sailoog 
for me the error looks like wrong time on client side

**Comment by free-x** [comment]
@sailoog 
another question: why do you use "bullseye" packages for ubuntu "focal"?

**Comment by sailoog** [comment]
> @sailoog for me the error looks like wrong time on client side

The time is OK but your certificate seems to be OK too so this should be on the client side. It is a Virtual machine, investigating...

EDITED: Solved, there was a corrupted apt cache, thanks.

**Comment by sailoog** [comment]
> @sailoog another question: why do you use "bullseye" packages for ubuntu "focal"?

We use only bullseye packages no matter what is the host system. On those repos there are only openplotter packages and when any of them needs dependencies, they will be loaded from focal or any official source. We do the same with OpenCPN but the inverse, we use focal PPA repos to install OpenCPN in bullseye.

If you do not have extra packages in https://www.free-x.de/deb4op bullseye that could create conflicts with official sources, everything should work as expected with xygrib and openplotter-avnav

**Comment by free-x** [comment]
I think I've already had a discussion like that. My point of view is that you should not do this. If you compare debian bullseye with ubuntu focal
qt5 5.15 vs 5.12
g++ 10.2.1 vs 9.3.0
et cetera. So do not know if the 100% ABI are compatible

**Comment by sailoog** [comment]
This has been working for OpenPlotter and OpenCPN packages for years and we are already survived to 2 Debian upgrades but you are right, we know this will work because we want this to work this way and we are the devs but this could not work for other apps we have no control like Xygrib. I will test that tomorrow and I will add an exception for that case if something does not work. This could be changed at any time if Xygrib gets broken in the future just updating openplotter-settings and changing sources.
