### ISSUE TITLE
pi4 manual install - FAILED. Unknown system: raspbian

### ISSUE THREAD

**Issue by Turnipisum** [openplotter/openplotter-settings#18]
Hi

Manual install on pi4 8gb bullseye got as far as settings install but it will not update when at source is clicked.
FAILED. Unknown system: raspbian

**Comment by FredericGuilbault** [comment]
I remember having problem when raspbeerrypi fundation break apart with raspbian community and decided to make their own operating system named raspios some identifiers of the operating system were not set correctly stipulating it's a debian or other incorrect names.

**Comment by sailoog** [comment]
This was already fixed, reopen if necessary.
