### ISSUE TITLE
Debian amd64 install does not have python3-rpi.gpio package 

### ISSUE THREAD

**Issue by FredericGuilbault** [openplotter/openplotter-settings#19]
Hi, I was about to give a try to OP3 in a VM, but the installation process stop on the error ` openplotter-i2c : Depends: python3-rpi.gpio but it is not installable`

Which make sense to not have i2c in a VM, but it's kinda sad to have it break completely as many other aspects of OP would still be useful.

Not sure how dpkg would be able to detect if the machine is a raspberry or not, but it surely it can detect the architecture and adjust its dependencies accordingly. To be coherent with the fact that the package is only available for the different arm arch, ( https://packages.debian.org/bullseye/python3-rpi.gpio ) . 

---
One way to address this could be to have different set of dependencies depending on the architecture: 

```
If the architecture-restricted dependency is part of a set of alternatives using |, that alternative is ignored completely on architectures that do not match the restriction. For example:

Build-Depends: foo [!i386] | bar [!amd64]

is equivalent to bar on the i386 architecture, to foo on the amd64 architecture, and to foo | bar on all other architectures.

```
( https://www.debian.org/doc/debian-policy/ch-relationships.html )

---
Maybe, another way would be to make the package optional, so amd64 users could cherry-pick the optional packages they want.

 
 <br><br><br><br>
 

--Fred
( I could dig this question further to save you guys\gals time if you want more info or have questions. )

**Comment by sailoog** [comment]
openplotter-i2c app is an optional package, if you are not running a raspberry you can not install this app from openplotter-settings

**Comment by FredericGuilbault** [comment]
`apt-get install openplotter-settings openplotter-i2c-` did the trick, thx.  
Should this issue stay open ?
