### ISSUE TITLE
App not responding - Issues - Contribute ?

### ISSUE THREAD

**Issue by ghost** [openplotter/openplotter-settings#26]
Hello there!

I wanted to leave a comment about the openplotter app (and all the others belonging the suite including OpenCPN, signal K installer etc.). There is a significant problem with the execution of these pieces of software as the UI is repeatedly "not responding" during runtime. You could tap on any button, try to enable|open|install anything, the UI will freeze with 100% probability and suggest you to force-close the app. Now I know that if I choose two wait (4-6 times in a row), the command I issued will finally be executed successfully, but is it really necessary to make users think that the app does not work at all ? Could we make something about this ? There is very little info about how to contribute to this project, finding the docs from the official website is already a challeng. I have been [trying] to use Openplotter on desktop and on RaspberryPi, because I like the project, but it definitely needs serious improvements, and I would be interested in helping at it instead of  spending my time trying to figure out how.

**Comment by sailoog** [comment]
https://openmarine.net/openplotter, where is the challenge?????

I have seen that behavior you are describing when installing OpenPlotter in Raspberry running old and not stable Ubuntu distributions. Obviously you are in an unusual scenario, try the official images and everything will work smoothly

**Comment by ghost** [comment]
Thank you a lot for your reply ! I am surprised I am the only one out there experiencing these issues. And I have used the official images from https://openplotter.readthedocs.io/en/latest/getting_started/downloading.html on both Raspberry (Pi4 with 4G of Ram) and un desktop with Ubuntu 22.04 LTS on an HP laptop (more or less the same resources as a Rasbperry Pi. I really don't understand why I have these issues, if I am really the only one.
