### ISSUE TITLE
 add sorces failes on ubuntu 22.04

### ISSUE THREAD

**Issue by vkuehn** [openplotter/openplotter-settings#28]
just installed open plotter in a VM on ubuntu 22.04 LTS. when adding sources it fails with

creating configuration directory /home/root/.openplotter
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/openplotterSettings/installSources.py", line 25, in main
conf2 = Conf()
File "/usr/lib/python3/dist-packages/openplotterSettings/conf.py", line 38, in init
os.mkdir(self.conf_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/root/.openplotter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/bin/settingsSourcesInstall", line 11, in
load_entry_point('openplotterSettings==3.6.6', 'console_scripts', 'settingsSourcesInstall')()
File "/usr/lib/python3/dist-packages/openplotterSettings/installSources.py", line 103, in main
except Exception as e: print(('FAILED: ')+str(e))
NameError: name '' is not defined

what can I do to fix that ?
is that a bug ? if so which script runs here ?

**Comment by sailoog** [comment]
Sorry the delay. Honestly OP v4 has not been tested enough in non Raspberry systems.

Are you running openplotter as root?

**Comment by vkuehn** [comment]
No not as root. 
As I saw some YT video where people installed it on a notebook can you give some hint what to start first ?

Would be more than happy to make it work and update the docs for it.

Even on a raspian it is not straight forward to know where to start on the commandline and development etc.

**Comment by sailoog** [comment]
Manual to install OP v4 in desktops and laptops

https://openplotter.readthedocs.io/en/4.x.x/getting_started/installing.html#desktop-and-laptop

After installing:

https://openplotter.readthedocs.io/en/4.x.x/settings/settings_app.html

Let me know any issue

**Comment by vkuehn** [comment]
yes I saw that and sorry if I didn't make it clear. I would like to run it from the sources. Do you have instructions for that ?

like I started openplotterSettings.py directly ended

`openplotterSettings.py", line 21, in <module>
    from .conf import Conf
ImportError: attempted relative import with no known parent package
`

**Comment by sailoog** [comment]
For development follow this: https://github.com/openplotter/openplotter-settings/blob/master/README.md

**Comment by vkuehn** [comment]
Thanks that does not look like the code could be easily debugged. 

I'll have a deeper look next week.

**Comment by vkuehn** [comment]
@sailoog did some investigations but I do not have the time currently to investigate further. 

However I wonder what your development.process is.

For now I will close that and have a look after the season

**Comment by mr3screen** [comment]
There seem to be 2 issues:
1) openplotter assumes the home directory for root is in /home/root. 
2) Somehow there is an undefined _() function (which is normally used for i18n of strings).

I'm trying to install it inside a docker container, so I'm using the root user.
As a workaround running `# mkdir -p /home/root/.openplotter` works.  `ln -s /root /home/root` might even be better.

---

... though installation does fail later for some. For example trying to install the signal K installer 4.3.0-stable leads to these loglines:
```
...
changed 628 packages in 35s

131 packages are looking for funding
  run `npm fund` for details
npm verbose cwd /tmp/openplotter
npm verbose os Linux 6.17.0-23-generic
npm verbose node v22.22.2
npm verbose npm  v10.9.7
npm verbose exit 0
npm info ok
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
Checking sources...
DONE
Installing/Updating signal K server...
DONE
Setting version...
DONE
```
and the RUN button stays deactivated when I select the signal K installer.

Installing the OpenCPN installer works but mentions a failure, which seems non-critical:
```
...
Failed to send reload request: No such file or directory
Checking sources...
DONE
Copying udev rules...
DONE
Setting version...
DONE
```
I also cannot click the RUN button for it, but I can invoke `# openplotter-opencpn-installer` from the terminal.
When I click Start, it outputs
```
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 https://deb.nodesource.com/node_22.x nodistro InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://www.free-x.de/deb4op bookworm InRelease
Hit:7 http://packages.ros.org/ros2/ubuntu jammy InRelease
Hit:8 http://packages.osrfoundation.org/gazebo/ubuntu-stable jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/opencpn/opencpn/ubuntu jammy InRelease
Get:10 https://dl.cloudsmith.io/public/openplotter/openplotter/deb/debian bookworm InRelease [11.5 kB]
Fetched 11.5 kB in 1s (14.4 kB/s)
Reading package lists...
Building dependency tree...
Reading state information...
23 packages can be upgraded. Run 'apt list --upgradable' to see them.
Failed to send reload request: No such file or directory
Checking sources...
DONE
Copying udev rules...
DONE
Setting version...
DONE
```
and the status bar says 'Done. Close this window and open the app again.', but rerunning the `openplotter-opencpn-installer` and re-starting the installation doesn't help. I can't find any `opencpn` executable.

Edit: I just saw I need to restart the `openplotter-settings`, not the opencpn-installer. Now the Open button is active for the OpenCPN Installer

**Comment by vkuehn** [comment]
@sailoog it would be really great if there is some none root installation possible even if that means the user has to be in some dedicated groups to access the hardware interfaces. Not sure if a closed issue is the right place to discuss @mr3screen but thanks a lot for your post !!
