### ISSUE TITLE
Support for Emlid Navio 2

### ISSUE THREAD

**Issue by maxekman** [openplotter/openplotter-settings#5]
I have a Emlid Navio 2 (https://emlid.com/navio/) drone autopilot/flightsystem which I'm planning to try to use with Open Plotter instead. Is the Moitessier project (https://github.com/openplotter/openplotter-moitessier) currently the best reference implementation for how to integrate sensors?

If I make any progress I'll be sure to share it and update the docs!

**Comment by sailoog** [comment]
Sorry for the delay. If your sensoris an IMU this is the place to look at: https://github.com/openplotter/openplotter-pypilot

For other I2C sensors this is the app: https://github.com/openplotter/openplotter-i2c

**Comment by maxekman** [comment]
Thanks! Will check it out.
