### ISSUE TITLE
Missing headless img 

### ISSUE THREAD

**Issue by jfexyz** [openplotter/openplotter-settings#6]
I am having some issues getting the NOOBS version up and running, so thought I would test the IMG version, but it's unavailable. Is the latest version of the Headless IMG broken? It seems to be missing from https://nx8035.your-storageshare.de/s/Yapesa2XPJptgaz

(Not sure where to post this issue; sorry if this is the wrong repo...)

**Comment by sailoog** [comment]
It was an error in the latest headless img version and we removed it to avoid confusion. This error has been fixed and headless img version will be available again on next updates.
