### ISSUE TITLE
Autostart settings removed after 2.4.1 update

### ISSUE THREAD

**Issue by Jamos1988** [openplotter/openplotter-settings#7]
Just updated the settings plugin, now the autostart options have been removed. OpenCPN starts automatically at boot still, but I cannot turn it off anymore. Checkbox for OpenCPN autostart is missing.

**Comment by sailoog** [comment]
I can not reproduce this issue, autostart options are working perfectly for me in openplotter-setings 2.4.1 and openplotter-opencpn-installer 2.2.1. Could you provide more details or screenshots?

**Comment by Jamos1988** [comment]
Yes, here is the screenshot: https://postimg.cc/xqNXsSb6
You can see in the General settings tab that the Autostart section has ben reduced, no checkbox is visible, tried maximizing the screen but this didn't help.

**Comment by Jamos1988** [comment]
*facepalm* I expected the setting to be there, but OpenCPN is ofcourse on the OpenCPN installer plugin. :( closing....
