### ISSUE TITLE
Unable to install "Signal K Installer" on Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by outdooracorn** [openplotter/openplotter-settings#8]
I installed `openplotter-settings` on Ubuntu 20.04 as per the [advanced install instructions](https://openplotter.readthedocs.io/en/latest/getting_started/installing.html#advanced) and proceeded to install all the apps. When I came to install the Signal K Installer I got an error. Trying to install `openplotter-signalk-installer` via the command line came up with this error:

```
$ sudo apt install openplotter-signalk-installer 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies.
 openplotter-signalk-installer : Depends: nodejs
E: Unable to correct problems, you have held broken packages.
```

Trying to install `nodejs` came up with a similar error complaining about an unmet dependency: `python-minimal`.

After some digging around I understood the problem to be that the nodejs package that was trying to be installed had the dependency `python-minimal` which was an alias for `python2-minimal`. Since there is no longer any support for Python2 it was removed in Ubuntu 20.04 Focal Fossa and the alias `python-minimal` didn't work.

The route course of this was that the apt sources file `/etc/apt/sources.list.d/openplotter.list` that is installed by `openplotter-settings` sets the distribution of the nodejs repository as `buster` (which I guess still had Python2 support and a working `python-minimal` alias) instead of `focal` (which is what is needed for Ubuntu 20.04 Focal Fossa). After manually changing `buster` to `focal` I was able to install `openplotter-signalk-installer`.

I think it would be sensible for `openplotter-settings` to use correct distribution when installing the `openplotter.list` file or let the nodesources setup script handle the adding of the nodejs sources (i.e. `curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -`).

**Comment by outdooracorn** [comment]
Had a quick look into the code. The issue seems to be in [installSources.py](https://github.com/openplotter/openplotter-settings/blob/654083d027ca1ee3ed52ee6f2ffdd1e319b4e5ec/openplotterSettings/installSources.py) where the distribution added to the  `openplotter.list` sources file is hardcoded. I'm happy to submit a PR to fix this by detecting the correct distribution to put in the sources file. Are you likely to accept such a PR?

**Comment by farotherside** [comment]
having this same error, also using Ubuntu 20.04.

**Comment by outdooracorn** [comment]
This is what my `/etc/apt/sources.list.d/openplotter.list` file looks like:
```
deb http://ppa.launchpad.net/opencpn/opencpn/ubuntu focal main
deb https://www.free-x.de/deb4op buster main
deb http://ppa.launchpad.net/openplotter/openplotter/ubuntu bionic main
deb https://repos.influxdata.com/debian buster stable
deb https://packages.grafana.com/oss/deb stable main
deb https://deb.nodesource.com/node_10.x focal main
deb-src https://deb.nodesource.com/node_10.x focal main
```
Changed the distro to `focal` on lines `1`, `6` and `7` (the others don't have releases for `focal`).

If you create this file ***before*** installing OpenPlotter you are all set.

---

If you have already tried to install OpenCPN and/or Signal K Server here are the steps (from the top of my head) I took:

- Remove the packages installed from the incorrect sources:
  `sudo apt autoremove openplotter-opencpn-installer openplotter-signalk-installer nodejs`

- Remove the `/usr/lib/node_modules` folder (if it exists) to remove any reminance of the previous attempt to install Signal K:
  `sudo rm -rv /usr/lib/node_modules`

- Remove the SignalK config folder:
  `sudo rm -rv ~/.signalk`

- Edit the `/etc/apt/sources.list.d/openplotter.list` file as above

- Update the apt sources:
  `sudo apt update`

- Go back to the OpenPlotter Settings app, "Refresh" the apps and install OpenCPN and Signal K Installer again.

---

I'll try and submit a PR to fix this soon.

**Comment by sailoog** [comment]
Sailing with limited connection right now, I will take a look at this in september

**Comment by sailoog** [comment]
Sorry for the delay, I have fixed this for Ubuntu Focal and trying to fix it also for Mint Ulyana. I will publish a new version soon, thanks for reporting.

**Comment by sailoog** [comment]
Done. v2.6.2-stable fixes this issue.  Now OP works in: 

- Raspberry OS buster
- Ubuntu focal
- Linux Mint ulyana
- Ubuntu groovy for Raspberry (beta)

Thanks for your help.
