### ISSUE TITLE
Question: arm64 support?

### ISSUE THREAD

**Issue by floviolleau** [openplotter/openplotter-settings#9]
Hi,

Thanks Openplotter's team for your amazing work.

I had a chance to use it in real life on a rpi 2 in France and it works quite well.
It is a bit slow due to the spec of the rpi and I'm looking for an upgrade solution.

I looked at those amazing SBC:
- Odroid N2+
- Rpi 4B 8Go

Both will run under arm64 and I'm wondering if it will work regarding the softwares?
I see that there is a big discussion on openCPN's github for CPU architectures
- https://github.com/OpenCPN/OpenCPN/issues/2047
- https://github.com/OpenCPN/OpenCPN/issues/2067

And on Odroid's forums:
- https://forum.odroid.com/viewtopic.php?p=273429#p273429

Will I need to compile all by myself?
Will Openplotter work by using openplotter-settings?
Do you plan to release any system images in arm64?

Thanks for your help

**Comment by sailoog** [comment]
This is the plan:

**Supported OS for Raspberry 3/4 boards**. This option is full featured.

- OpenPlotter pre-compiled images based on Raspberry OS 32-bit: currently supported.
- OpenPlotter pre-compiled images based on Raspberry OS 64-bit: will be supported after the official release of Raspberry OS 64-bit.
- OpenPlotter manually installed on [Ubuntu 64-bit for Raspberry](https://ubuntu.com/download/raspberry-pi): under construction.

**Supported OS for other boards (amd64, arm64)**. Options marked as "only for Raspberry" will not work here.
- OpenPlotter manually installed on any OS based on Debian (Ubuntu, Mint...): under construction.

**Supported OS for other boards (armhf, i386)**. Options marked as "only for Raspberry" will not work here.
- OpenPlotter manually installed on any OS based on Debian (Ubuntu, Mint...): Deprecated. Maybe it works but we will not maintain them.

**Comment by floviolleau** [comment]
Hi,

Thanks for the fast and precise answer 👍 .

When you mentioned:

> Options marked as "only for Raspberry" will not work here

I searched in the docs and on the repository but I wasn't able to see where can I have the list of options with this tag "only for Rpi" in order to see if it is a blocker for me or not?

Thanks

**Comment by sailoog** [comment]
https://openplotter.readthedocs.io/en/latest/getting_started/downloading.html#advanced
